
name: Extract src.zip
on:
  push:
    paths:
      - 'src.zip'

jobs:
  extract-src-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Create src directory
      run: mkdir -p src
      working-directory: ${{ github.workspace }}

    - name: List files in workspace
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: Extract src.zip
      run: unzip ${{ github.workspace }}/src.zip -d ${{ github.workspace }}/src
      working-directory: ${{ github.workspace }}

    - name: List files in src directory
      run: ls -R src
      working-directory: ${{ github.workspace }}
